version: "3.9"

services:
  ocr:
    build: ./server/ocr
    image: alex-ocr:latest
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  tts:
    build: ./server/tts
    image: alex-tts:latest
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  api:
    build: ./server/api
    image: alex-api:latest
    ports:
      - "8080:8080"
    depends_on:
      - ocr
      - tts
