services:
  ocr:
    build:
      context: .
      dockerfile: server/ocr/Dockerfile
    image: alex-ocr:latest
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  tts:
    build:
      context: .
      dockerfile: server/tts/Dockerfile
    image: alex-tts:latest
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  api:
    build:
      context: .
      dockerfile: server/api/Dockerfile
    image: alex-api:latest
    ports:
      - "8080:8080"
    depends_on:
      - ocr
      - tts
